version: "1.0"
services:
  db:
    container_name: artist-music-db
    build: "build/mysql"
    platform: linux/amd64
    ports:
      - "${MYSQL_PORT}:3306"
    restart: always
    volumes:
      - ./tmp/tmp_mysql:/tmp --user 1000
      - ./tmp/src-db_volume:/var/lib/mysql --user 1000
    environment:
      MYSQL_ROOT_PASSWORD: artist_pass
      MYSQL_DATABASE: db-artist-music
      MYSQL_USER: artist_user
      MYSQL_PASSWORD: artist_pass
    command: mysqld --sql_mode=""
  api:
    container_name: artist-music-api
    build:
      context: .
      dockerfile: build/web/Dockerfile
    env_file:
      - .env
    volumes:
      - ./:/opt/src
    ports:
      - "${WEB_PORT}:3000"
    depends_on:
      - db
    tty: true
    stdin_open: true
